version: 2
jobs:
  deployMaster:
    docker:
      - image: circleci/node:10.9.0
    working_directory: ~/repo
    steps:
      - checkout
      # remove node_modules
      - run: rm -rf node_modules
      # install sshpass
      - run:
          name: install sshpass
          command: |
            sudo apt-get install sshpass
      # changing perssion
      - run: chmod +x ./.circleci/deployDev.sh
      # deploy and start server
      - run: ./.circleci/deployDev.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      # - test
      - deployMaster:
          # requires:
          #   - test
          filters:
            branches:
              only: master
